import type * as MonacoT from "monaco-editor";

type Monaco = typeof MonacoT;
type SnippetLang = "python" | "javascript" | "java" | "cpp";

interface SnippetDef {
  label: string;
  detail: string;
  body: string;
  documentation?: string;
  aliases?: string[];
}

const PYTHON_SNIPPETS: SnippetDef[] = [
  {
    label: "for",
    detail: "for i in range(n)",
    body: "for ${1:i} in range(${2:n}):\n\t${0:pass}",
  },
  {
    label: "forenum",
    detail: "for i, x in enumerate(arr)",
    body: "for ${1:i}, ${2:x} in enumerate(${3:arr}):\n\t${0:pass}",
    aliases: ["enumerate"],
  },
  {
    label: "forin",
    detail: "for x in arr",
    body: "for ${1:x} in ${2:arr}:\n\t${0:pass}",
  },
  {
    label: "while",
    detail: "while condition",
    body: "while ${1:condition}:\n\t${0:pass}",
  },
  {
    label: "whiletwo",
    detail: "two-pointer while loop",
    body: "l, r = 0, len(${1:nums}) - 1\nwhile l < r:\n\t${0:pass}",
    aliases: ["twopointer", "twopointers"],
  },
  {
    label: "window",
    detail: "sliding window template",
    body: [
      "l = 0",
      "for r in range(len(${1:nums})):",
      "\t${2:# expand window with nums[r]}",
      "\twhile ${3:condition}:",
      "\t\t${4:# shrink window from nums[l]}",
      "\t\tl += 1",
      "\t${0:# update answer}",
    ].join("\n"),
    aliases: ["sliding", "slidingwindow"],
  },
  {
    label: "prefix",
    detail: "prefix sum array",
    body: [
      "prefix = [0] * (len(${1:nums}) + 1)",
      "for i, x in enumerate(${1:nums}):",
      "\tprefix[i + 1] = prefix[i] + x",
      "$0",
    ].join("\n"),
    aliases: ["prefixsum", "cumsum"],
  },
  {
    label: "ifmain",
    detail: "if __name__ == '__main__':",
    body: 'if __name__ == "__main__":\n\t${0:pass}',
  },
  {
    label: "dd",
    detail: "defaultdict(list)",
    body: "${1:groups} = defaultdict(${2:list})",
    documentation: "Requires: from collections import defaultdict",
    aliases: ["defaultdict"],
  },
  {
    label: "ddint",
    detail: "defaultdict(int) counter",
    body: "${1:count} = defaultdict(int)",
    aliases: ["defaultdict"],
  },
  {
    label: "ctr",
    detail: "Counter(iterable)",
    body: "${1:count} = Counter(${2:nums})",
    documentation: "Requires: from collections import Counter",
    aliases: ["counter"],
  },
  {
    label: "dq",
    detail: "deque([...])",
    body: "${1:queue} = deque([${2}])",
    documentation: "Requires: from collections import deque",
    aliases: ["deque"],
  },
  {
    label: "heap",
    detail: "heap push/pop",
    body: "${1:heap} = []\nheapq.heappush(${1:heap}, ${2:val})\n${3:top} = heapq.heappop(${1:heap})",
    documentation: "Requires: import heapq",
    aliases: ["heapq", "priorityqueue", "pq"],
  },
  {
    label: "bfs",
    detail: "BFS template (grid / graph)",
    body: [
      "queue = deque([${1:start}])",
      "visited = {${1:start}}",
      "while queue:",
      "\t${2:node} = queue.popleft()",
      "\tfor ${3:nxt} in ${4:neighbors(${2:node})}:",
      "\t\tif ${3:nxt} not in visited:",
      "\t\t\tvisited.add(${3:nxt})",
      "\t\t\tqueue.append(${3:nxt})",
      "\t\t\t$0",
    ].join("\n"),
    documentation: "Requires: from collections import deque",
    aliases: ["breadthfirst", "breadth"],
  },
  {
    label: "dfs",
    detail: "DFS recursive template",
    body: [
      "def dfs(${1:node}):",
      "\tif not ${1:node}:",
      "\t\treturn",
      "\t${2:# process}",
      "\tfor ${3:nxt} in ${4:neighbors(${1:node})}:",
      "\t\tdfs(${3:nxt})",
      "",
      "dfs(${5:start})",
      "$0",
    ].join("\n"),
    aliases: ["depthfirst", "depth"],
  },
  {
    label: "binsearch",
    detail: "Binary search template",
    body: [
      "l, r = 0, len(${1:nums}) - 1",
      "while l <= r:",
      "\tmid = (l + r) // 2",
      "\tif ${1:nums}[mid] == ${2:target}:",
      "\t\treturn mid",
      "\telif ${1:nums}[mid] < ${2:target}:",
      "\t\tl = mid + 1",
      "\telse:",
      "\t\tr = mid - 1",
      "return -1",
    ].join("\n"),
    aliases: ["binarysearch", "bsearch"],
  },
  {
    label: "bisect",
    detail: "bisect_left lower bound",
    body: [
      "l, r = 0, len(${1:nums})",
      "while l < r:",
      "\tmid = (l + r) // 2",
      "\tif ${1:nums}[mid] < ${2:target}:",
      "\t\tl = mid + 1",
      "\telse:",
      "\t\tr = mid",
      "return l",
    ].join("\n"),
    aliases: ["lowerbound"],
  },
  {
    label: "treenode",
    detail: "TreeNode class",
    body: [
      "class TreeNode:",
      "\tdef __init__(self, val=0, left=None, right=None):",
      "\t\tself.val = val",
      "\t\tself.left = left",
      "\t\tself.right = right",
    ].join("\n"),
  },
  {
    label: "listnode",
    detail: "ListNode class",
    body: [
      "class ListNode:",
      "\tdef __init__(self, val=0, next=None):",
      "\t\tself.val = val",
      "\t\tself.next = next",
    ].join("\n"),
  },
  {
    label: "trie",
    detail: "Trie class",
    body: [
      "class Trie:",
      "\tdef __init__(self):",
      "\t\tself.children = {}",
      "\t\tself.end = False",
      "",
      "\tdef insert(self, word):",
      "\t\tnode = self",
      "\t\tfor c in word:",
      "\t\t\tnode = node.children.setdefault(c, Trie())",
      "\t\tnode.end = True",
      "",
      "\tdef search(self, word):",
      "\t\tnode = self",
      "\t\tfor c in word:",
      "\t\t\tif c not in node.children:",
      "\t\t\t\treturn False",
      "\t\t\tnode = node.children[c]",
      "\t\treturn node.end",
      "$0",
    ].join("\n"),
    aliases: ["prefixtree"],
  },
  {
    label: "unionfind",
    detail: "Union-Find / DSU",
    body: [
      "class UnionFind:",
      "\tdef __init__(self, n):",
      "\t\tself.parent = list(range(n))",
      "\t\tself.rank = [0] * n",
      "\t\tself.count = n",
      "",
      "\tdef find(self, x):",
      "\t\twhile self.parent[x] != x:",
      "\t\t\tself.parent[x] = self.parent[self.parent[x]]",
      "\t\t\tx = self.parent[x]",
      "\t\treturn x",
      "",
      "\tdef union(self, a, b):",
      "\t\tra, rb = self.find(a), self.find(b)",
      "\t\tif ra == rb:",
      "\t\t\treturn False",
      "\t\tif self.rank[ra] < self.rank[rb]:",
      "\t\t\tra, rb = rb, ra",
      "\t\tself.parent[rb] = ra",
      "\t\tif self.rank[ra] == self.rank[rb]:",
      "\t\t\tself.rank[ra] += 1",
      "\t\tself.count -= 1",
      "\t\treturn True",
      "$0",
    ].join("\n"),
    aliases: ["dsu", "disjointset", "uf"],
  },
  {
    label: "topo",
    detail: "Topological sort (Kahn's)",
    body: [
      "indeg = [0] * ${1:n}",
      "graph = defaultdict(list)",
      "for u, v in ${2:edges}:",
      "\tgraph[u].append(v)",
      "\tindeg[v] += 1",
      "queue = deque(i for i in range(${1:n}) if indeg[i] == 0)",
      "order = []",
      "while queue:",
      "\tnode = queue.popleft()",
      "\torder.append(node)",
      "\tfor nxt in graph[node]:",
      "\t\tindeg[nxt] -= 1",
      "\t\tif indeg[nxt] == 0:",
      "\t\t\tqueue.append(nxt)",
      "$0",
    ].join("\n"),
    documentation: "Requires: from collections import defaultdict, deque",
    aliases: ["topological", "kahn"],
  },
  {
    label: "dijkstra",
    detail: "Dijkstra shortest path",
    body: [
      "dist = {${1:start}: 0}",
      "heap = [(0, ${1:start})]",
      "while heap:",
      "\td, node = heapq.heappop(heap)",
      "\tif d > dist[node]:",
      "\t\tcontinue",
      "\tfor nxt, w in ${2:graph}[node]:",
      "\t\tnd = d + w",
      "\t\tif nd < dist.get(nxt, float('inf')):",
      "\t\t\tdist[nxt] = nd",
      "\t\t\theapq.heappush(heap, (nd, nxt))",
      "$0",
    ].join("\n"),
    documentation: "Requires: import heapq",
    aliases: ["shortestpath"],
  },
  {
    label: "memo",
    detail: "@lru_cache memoization",
    body: "@lru_cache(maxsize=None)\ndef ${1:helper}(${2:args}):\n\t$0",
    documentation: "Requires: from functools import lru_cache or functools.cache",
    aliases: ["cache", "lrucache"],
  },
  {
    label: "cache",
    detail: "@cache memoization (py3.9+)",
    body: "@cache\ndef ${1:helper}(${2:args}):\n\t$0",
    documentation: "Requires: from functools import cache",
  },
  {
    label: "imp",
    detail: "Common LeetCode imports",
    body: [
      "from collections import defaultdict, Counter, deque",
      "from heapq import heappush, heappop, heapify",
      "from functools import lru_cache, cache",
      "from typing import List, Optional",
      "$0",
    ].join("\n"),
    aliases: ["imports"],
  },
  {
    label: "solclass",
    detail: "LeetCode Solution class",
    body: [
      "class Solution:",
      "\tdef ${1:methodName}(self, ${2:nums}: List[int]) -> ${3:int}:",
      "\t\t$0",
    ].join("\n"),
    aliases: ["solution"],
  },
];

const JS_SNIPPETS: SnippetDef[] = [
  {
    label: "for",
    detail: "for (let i = 0; i < n; i++)",
    body: "for (let ${1:i} = 0; ${1:i} < ${2:arr}.length; ${1:i}++) {\n\t$0\n}",
  },
  {
    label: "forof",
    detail: "for (const x of arr)",
    body: "for (const ${1:x} of ${2:arr}) {\n\t$0\n}",
  },
  {
    label: "forin",
    detail: "for (const k in obj)",
    body: "for (const ${1:key} in ${2:obj}) {\n\t$0\n}",
  },
  {
    label: "forent",
    detail: "for (const [k, v] of Object.entries)",
    body: "for (const [${1:key}, ${2:val}] of Object.entries(${3:obj})) {\n\t$0\n}",
    aliases: ["entries"],
  },
  {
    label: "while",
    detail: "while (condition)",
    body: "while (${1:condition}) {\n\t$0\n}",
  },
  {
    label: "whiletwo",
    detail: "two-pointer while loop",
    body: "let l = 0, r = ${1:nums}.length - 1;\nwhile (l < r) {\n\t$0\n}",
    aliases: ["twopointer", "twopointers"],
  },
  {
    label: "window",
    detail: "sliding window template",
    body: [
      "let l = 0;",
      "for (let r = 0; r < ${1:nums}.length; r++) {",
      "\t${2:// expand window with nums[r]}",
      "\twhile (${3:condition}) {",
      "\t\t${4:// shrink window from nums[l]}",
      "\t\tl++;",
      "\t}",
      "\t${0:// update answer}",
      "}",
    ].join("\n"),
    aliases: ["sliding", "slidingwindow"],
  },
  {
    label: "prefix",
    detail: "prefix sum array",
    body: [
      "const prefix = new Array(${1:nums}.length + 1).fill(0);",
      "for (let i = 0; i < ${1:nums}.length; i++) {",
      "\tprefix[i + 1] = prefix[i] + ${1:nums}[i];",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["prefixsum", "cumsum"],
  },
  {
    label: "map",
    detail: "const m = new Map()",
    body: "const ${1:map} = new Map();",
  },
  {
    label: "set",
    detail: "const s = new Set()",
    body: "const ${1:set} = new Set(${2});",
  },
  {
    label: "freq",
    detail: "frequency map from array",
    body: [
      "const freq = new Map();",
      "for (const x of ${1:arr}) {",
      "\tfreq.set(x, (freq.get(x) ?? 0) + 1);",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["counter", "frequency"],
  },
  {
    label: "bfs",
    detail: "BFS template",
    body: [
      "const queue = [${1:start}];",
      "const visited = new Set([${1:start}]);",
      "while (queue.length) {",
      "\tconst ${2:node} = queue.shift();",
      "\tfor (const ${3:nxt} of ${4:neighbors(${2:node})}) {",
      "\t\tif (!visited.has(${3:nxt})) {",
      "\t\t\tvisited.add(${3:nxt});",
      "\t\t\tqueue.push(${3:nxt});",
      "\t\t\t$0",
      "\t\t}",
      "\t}",
      "}",
    ].join("\n"),
    aliases: ["breadthfirst", "breadth"],
  },
  {
    label: "dfs",
    detail: "DFS recursive template",
    body: [
      "const dfs = (${1:node}) => {",
      "\tif (!${1:node}) return;",
      "\t${2:// process}",
      "\tfor (const ${3:nxt} of ${4:neighbors(${1:node})}) {",
      "\t\tdfs(${3:nxt});",
      "\t}",
      "};",
      "dfs(${5:start});",
      "$0",
    ].join("\n"),
    aliases: ["depthfirst", "depth"],
  },
  {
    label: "binsearch",
    detail: "Binary search template",
    body: [
      "let l = 0, r = ${1:nums}.length - 1;",
      "while (l <= r) {",
      "\tconst mid = (l + r) >> 1;",
      "\tif (${1:nums}[mid] === ${2:target}) return mid;",
      "\tif (${1:nums}[mid] < ${2:target}) l = mid + 1;",
      "\telse r = mid - 1;",
      "}",
      "return -1;",
    ].join("\n"),
    aliases: ["binarysearch", "bsearch"],
  },
  {
    label: "treenode",
    detail: "TreeNode constructor",
    body: "function TreeNode(val, left, right) {\n\tthis.val = val ?? 0;\n\tthis.left = left ?? null;\n\tthis.right = right ?? null;\n}",
  },
  {
    label: "listnode",
    detail: "ListNode constructor",
    body: "function ListNode(val, next) {\n\tthis.val = val ?? 0;\n\tthis.next = next ?? null;\n}",
  },
  {
    label: "trie",
    detail: "Trie class",
    body: [
      "class Trie {",
      "\tconstructor() {",
      "\t\tthis.children = new Map();",
      "\t\tthis.end = false;",
      "\t}",
      "\tinsert(word) {",
      "\t\tlet node = this;",
      "\t\tfor (const c of word) {",
      "\t\t\tif (!node.children.has(c)) node.children.set(c, new Trie());",
      "\t\t\tnode = node.children.get(c);",
      "\t\t}",
      "\t\tnode.end = true;",
      "\t}",
      "\tsearch(word) {",
      "\t\tlet node = this;",
      "\t\tfor (const c of word) {",
      "\t\t\tif (!node.children.has(c)) return false;",
      "\t\t\tnode = node.children.get(c);",
      "\t\t}",
      "\t\treturn node.end;",
      "\t}",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["prefixtree"],
  },
  {
    label: "unionfind",
    detail: "Union-Find / DSU",
    body: [
      "class UnionFind {",
      "\tconstructor(n) {",
      "\t\tthis.parent = Array.from({ length: n }, (_, i) => i);",
      "\t\tthis.rank = new Array(n).fill(0);",
      "\t\tthis.count = n;",
      "\t}",
      "\tfind(x) {",
      "\t\twhile (this.parent[x] !== x) {",
      "\t\t\tthis.parent[x] = this.parent[this.parent[x]];",
      "\t\t\tx = this.parent[x];",
      "\t\t}",
      "\t\treturn x;",
      "\t}",
      "\tunion(a, b) {",
      "\t\tlet ra = this.find(a), rb = this.find(b);",
      "\t\tif (ra === rb) return false;",
      "\t\tif (this.rank[ra] < this.rank[rb]) [ra, rb] = [rb, ra];",
      "\t\tthis.parent[rb] = ra;",
      "\t\tif (this.rank[ra] === this.rank[rb]) this.rank[ra]++;",
      "\t\tthis.count--;",
      "\t\treturn true;",
      "\t}",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["dsu", "disjointset", "uf"],
  },
  {
    label: "memo",
    detail: "Memoization with Map",
    body: [
      "const memo = new Map();",
      "const ${1:helper} = (${2:key}) => {",
      "\tif (memo.has(${2:key})) return memo.get(${2:key});",
      "\t$0",
      "\tmemo.set(${2:key}, result);",
      "\treturn result;",
      "};",
    ].join("\n"),
    aliases: ["cache"],
  },
];

const JAVA_SNIPPETS: SnippetDef[] = [
  {
    label: "for",
    detail: "for (int i = 0; i < n; i++)",
    body: "for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}",
  },
  {
    label: "forarr",
    detail: "for (int i = 0; i < arr.length; i++)",
    body: "for (int ${1:i} = 0; ${1:i} < ${2:arr}.length; ${1:i}++) {\n\t$0\n}",
  },
  {
    label: "foreach",
    detail: "for (T x : arr)",
    body: "for (${1:int} ${2:x} : ${3:arr}) {\n\t$0\n}",
    aliases: ["enhanced"],
  },
  {
    label: "while",
    detail: "while (condition)",
    body: "while (${1:condition}) {\n\t$0\n}",
  },
  {
    label: "whiletwo",
    detail: "two-pointer while loop",
    body: "int l = 0, r = ${1:nums}.length - 1;\nwhile (l < r) {\n\t$0\n}",
    aliases: ["twopointer", "twopointers"],
  },
  {
    label: "window",
    detail: "sliding window template",
    body: [
      "int l = 0;",
      "for (int r = 0; r < ${1:nums}.length; r++) {",
      "\t${2:// expand window with nums[r]}",
      "\twhile (${3:condition}) {",
      "\t\t${4:// shrink window from nums[l]}",
      "\t\tl++;",
      "\t}",
      "\t${0:// update answer}",
      "}",
    ].join("\n"),
    aliases: ["sliding", "slidingwindow"],
  },
  {
    label: "prefix",
    detail: "prefix sum array",
    body: [
      "int[] prefix = new int[${1:nums}.length + 1];",
      "for (int i = 0; i < ${1:nums}.length; i++) {",
      "\tprefix[i + 1] = prefix[i] + ${1:nums}[i];",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["prefixsum", "cumsum"],
  },
  {
    label: "map",
    detail: "HashMap<K, V>",
    body: "Map<${1:Integer}, ${2:Integer}> ${3:map} = new HashMap<>();",
    documentation: "Requires: import java.util.*;",
  },
  {
    label: "set",
    detail: "HashSet<T>",
    body: "Set<${1:Integer}> ${2:set} = new HashSet<>();",
    documentation: "Requires: import java.util.*;",
  },
  {
    label: "list",
    detail: "ArrayList<T>",
    body: "List<${1:Integer}> ${2:list} = new ArrayList<>();",
    documentation: "Requires: import java.util.*;",
  },
  {
    label: "deque",
    detail: "ArrayDeque<T>",
    body: "Deque<${1:Integer}> ${2:queue} = new ArrayDeque<>();",
    aliases: ["queue"],
    documentation: "Requires: import java.util.*;",
  },
  {
    label: "pq",
    detail: "PriorityQueue<T>",
    body: "PriorityQueue<${1:Integer}> ${2:pq} = new PriorityQueue<>();",
    aliases: ["priorityqueue", "heap"],
    documentation: "Requires: import java.util.*;",
  },
  {
    label: "freq",
    detail: "frequency map from int[]",
    body: [
      "Map<Integer, Integer> freq = new HashMap<>();",
      "for (int x : ${1:arr}) {",
      "\tfreq.merge(x, 1, Integer::sum);",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["counter", "frequency"],
  },
  {
    label: "bfs",
    detail: "BFS template",
    body: [
      "Deque<${1:Integer}> queue = new ArrayDeque<>();",
      "Set<${1:Integer}> visited = new HashSet<>();",
      "queue.offer(${2:start});",
      "visited.add(${2:start});",
      "while (!queue.isEmpty()) {",
      "\t${1:Integer} node = queue.poll();",
      "\tfor (${1:Integer} nxt : ${3:neighbors(node)}) {",
      "\t\tif (visited.add(nxt)) {",
      "\t\t\tqueue.offer(nxt);",
      "\t\t\t$0",
      "\t\t}",
      "\t}",
      "}",
    ].join("\n"),
    aliases: ["breadthfirst", "breadth"],
  },
  {
    label: "dfs",
    detail: "DFS recursive template",
    body: [
      "private void dfs(${1:int} node) {",
      "\t${2:// process}",
      "\tfor (${1:int} nxt : ${3:neighbors(node)}) {",
      "\t\tdfs(nxt);",
      "\t}",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["depthfirst", "depth"],
  },
  {
    label: "binsearch",
    detail: "Binary search template",
    body: [
      "int l = 0, r = ${1:nums}.length - 1;",
      "while (l <= r) {",
      "\tint mid = (l + r) >>> 1;",
      "\tif (${1:nums}[mid] == ${2:target}) return mid;",
      "\tif (${1:nums}[mid] < ${2:target}) l = mid + 1;",
      "\telse r = mid - 1;",
      "}",
      "return -1;",
    ].join("\n"),
    aliases: ["binarysearch", "bsearch"],
  },
  {
    label: "treenode",
    detail: "TreeNode class",
    body: [
      "class TreeNode {",
      "\tint val;",
      "\tTreeNode left, right;",
      "\tTreeNode() {}",
      "\tTreeNode(int val) { this.val = val; }",
      "\tTreeNode(int val, TreeNode left, TreeNode right) {",
      "\t\tthis.val = val; this.left = left; this.right = right;",
      "\t}",
      "}",
    ].join("\n"),
  },
  {
    label: "listnode",
    detail: "ListNode class",
    body: [
      "class ListNode {",
      "\tint val;",
      "\tListNode next;",
      "\tListNode() {}",
      "\tListNode(int val) { this.val = val; }",
      "\tListNode(int val, ListNode next) { this.val = val; this.next = next; }",
      "}",
    ].join("\n"),
  },
  {
    label: "unionfind",
    detail: "Union-Find / DSU",
    body: [
      "class UnionFind {",
      "\tint[] parent, rank;",
      "\tint count;",
      "\tUnionFind(int n) {",
      "\t\tparent = new int[n];",
      "\t\trank = new int[n];",
      "\t\tcount = n;",
      "\t\tfor (int i = 0; i < n; i++) parent[i] = i;",
      "\t}",
      "\tint find(int x) {",
      "\t\twhile (parent[x] != x) {",
      "\t\t\tparent[x] = parent[parent[x]];",
      "\t\t\tx = parent[x];",
      "\t\t}",
      "\t\treturn x;",
      "\t}",
      "\tboolean union(int a, int b) {",
      "\t\tint ra = find(a), rb = find(b);",
      "\t\tif (ra == rb) return false;",
      "\t\tif (rank[ra] < rank[rb]) { int t = ra; ra = rb; rb = t; }",
      "\t\tparent[rb] = ra;",
      "\t\tif (rank[ra] == rank[rb]) rank[ra]++;",
      "\t\tcount--;",
      "\t\treturn true;",
      "\t}",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["dsu", "disjointset", "uf"],
  },
  {
    label: "sout",
    detail: "System.out.println",
    body: "System.out.println(${1});",
    aliases: ["println", "print"],
  },
  {
    label: "imp",
    detail: "Common LeetCode imports",
    body: "import java.util.*;\n$0",
    aliases: ["imports"],
  },
];

const CPP_SNIPPETS: SnippetDef[] = [
  {
    label: "for",
    detail: "for (int i = 0; i < n; ++i)",
    body: "for (int ${1:i} = 0; ${1:i} < ${2:n}; ++${1:i}) {\n\t$0\n}",
  },
  {
    label: "foreach",
    detail: "for (auto& x : arr)",
    body: "for (${1:auto}& ${2:x} : ${3:arr}) {\n\t$0\n}",
    aliases: ["rangefor"],
  },
  {
    label: "while",
    detail: "while (condition)",
    body: "while (${1:condition}) {\n\t$0\n}",
  },
  {
    label: "whiletwo",
    detail: "two-pointer while loop",
    body: "int l = 0, r = (int)${1:nums}.size() - 1;\nwhile (l < r) {\n\t$0\n}",
    aliases: ["twopointer", "twopointers"],
  },
  {
    label: "window",
    detail: "sliding window template",
    body: [
      "int l = 0;",
      "for (int r = 0; r < (int)${1:nums}.size(); ++r) {",
      "\t${2:// expand window with nums[r]}",
      "\twhile (${3:condition}) {",
      "\t\t${4:// shrink window from nums[l]}",
      "\t\t++l;",
      "\t}",
      "\t${0:// update answer}",
      "}",
    ].join("\n"),
    aliases: ["sliding", "slidingwindow"],
  },
  {
    label: "prefix",
    detail: "prefix sum vector",
    body: [
      "vector<long long> prefix(${1:nums}.size() + 1, 0);",
      "for (int i = 0; i < (int)${1:nums}.size(); ++i) {",
      "\tprefix[i + 1] = prefix[i] + ${1:nums}[i];",
      "}",
      "$0",
    ].join("\n"),
    aliases: ["prefixsum", "cumsum"],
  },
  {
    label: "vec",
    detail: "vector<T>",
    body: "vector<${1:int}> ${2:v};",
    aliases: ["vector"],
  },
  {
    label: "vec2d",
    detail: "vector<vector<T>>(n, vector<T>(m))",
    body: "vector<vector<${1:int}>> ${2:grid}(${3:n}, vector<${1:int}>(${4:m}, ${5:0}));",
    aliases: ["vector2d", "grid"],
  },
  {
    label: "umap",
    detail: "unordered_map<K, V>",
    body: "unordered_map<${1:int}, ${2:int}> ${3:mp};",
    aliases: ["hashmap"],
  },
  {
    label: "uset",
    detail: "unordered_set<T>",
    body: "unordered_set<${1:int}> ${2:st};",
    aliases: ["hashset"],
  },
  {
    label: "pq",
    detail: "priority_queue<T> (max-heap)",
    body: "priority_queue<${1:int}> ${2:pq};",
    aliases: ["heap", "priorityqueue"],
  },
  {
    label: "pqmin",
    detail: "priority_queue min-heap",
    body: "priority_queue<${1:int}, vector<${1:int}>, greater<${1:int}>> ${2:pq};",
    aliases: ["minheap"],
  },
  {
    label: "dq",
    detail: "deque<T>",
    body: "deque<${1:int}> ${2:dq};",
    aliases: ["deque"],
  },
  {
    label: "freq",
    detail: "frequency map from vector",
    body: [
      "unordered_map<int, int> freq;",
      "for (int x : ${1:arr}) ++freq[x];",
      "$0",
    ].join("\n"),
    aliases: ["counter", "frequency"],
  },
  {
    label: "bfs",
    detail: "BFS template",
    body: [
      "queue<${1:int}> q;",
      "unordered_set<${1:int}> visited;",
      "q.push(${2:start});",
      "visited.insert(${2:start});",
      "while (!q.empty()) {",
      "\t${1:int} node = q.front(); q.pop();",
      "\tfor (${1:int} nxt : ${3:neighbors(node)}) {",
      "\t\tif (visited.insert(nxt).second) {",
      "\t\t\tq.push(nxt);",
      "\t\t\t$0",
      "\t\t}",
      "\t}",
      "}",
    ].join("\n"),
    aliases: ["breadthfirst", "breadth"],
  },
  {
    label: "dfs",
    detail: "DFS recursive template",
    body: [
      "function<void(${1:int})> dfs = [&](${1:int} node) {",
      "\t${2:// process}",
      "\tfor (${1:int} nxt : ${3:neighbors(node)}) {",
      "\t\tdfs(nxt);",
      "\t}",
      "};",
      "dfs(${4:start});",
      "$0",
    ].join("\n"),
    aliases: ["depthfirst", "depth"],
  },
  {
    label: "binsearch",
    detail: "Binary search template",
    body: [
      "int l = 0, r = (int)${1:nums}.size() - 1;",
      "while (l <= r) {",
      "\tint mid = l + (r - l) / 2;",
      "\tif (${1:nums}[mid] == ${2:target}) return mid;",
      "\tif (${1:nums}[mid] < ${2:target}) l = mid + 1;",
      "\telse r = mid - 1;",
      "}",
      "return -1;",
    ].join("\n"),
    aliases: ["binarysearch", "bsearch"],
  },
  {
    label: "treenode",
    detail: "TreeNode struct",
    body: [
      "struct TreeNode {",
      "\tint val;",
      "\tTreeNode *left, *right;",
      "\tTreeNode() : val(0), left(nullptr), right(nullptr) {}",
      "\tTreeNode(int x) : val(x), left(nullptr), right(nullptr) {}",
      "\tTreeNode(int x, TreeNode *l, TreeNode *r) : val(x), left(l), right(r) {}",
      "};",
    ].join("\n"),
  },
  {
    label: "listnode",
    detail: "ListNode struct",
    body: [
      "struct ListNode {",
      "\tint val;",
      "\tListNode *next;",
      "\tListNode() : val(0), next(nullptr) {}",
      "\tListNode(int x) : val(x), next(nullptr) {}",
      "\tListNode(int x, ListNode *n) : val(x), next(n) {}",
      "};",
    ].join("\n"),
  },
  {
    label: "unionfind",
    detail: "Union-Find / DSU",
    body: [
      "struct UnionFind {",
      "\tvector<int> parent, rank_;",
      "\tint count;",
      "\tUnionFind(int n) : parent(n), rank_(n, 0), count(n) {",
      "\t\tiota(parent.begin(), parent.end(), 0);",
      "\t}",
      "\tint find(int x) {",
      "\t\twhile (parent[x] != x) {",
      "\t\t\tparent[x] = parent[parent[x]];",
      "\t\t\tx = parent[x];",
      "\t\t}",
      "\t\treturn x;",
      "\t}",
      "\tbool unite(int a, int b) {",
      "\t\tint ra = find(a), rb = find(b);",
      "\t\tif (ra == rb) return false;",
      "\t\tif (rank_[ra] < rank_[rb]) swap(ra, rb);",
      "\t\tparent[rb] = ra;",
      "\t\tif (rank_[ra] == rank_[rb]) ++rank_[ra];",
      "\t\t--count;",
      "\t\treturn true;",
      "\t}",
      "};",
      "$0",
    ].join("\n"),
    aliases: ["dsu", "disjointset", "uf"],
  },
  {
    label: "imp",
    detail: "Common LeetCode includes",
    body: "#include <bits/stdc++.h>\nusing namespace std;\n$0",
    aliases: ["includes", "bits"],
  },
];

function buildSortText(index: number): string {
  return index.toString(36).padStart(3, "0");
}

function buildFilterText(s: SnippetDef): string {
  if (!s.aliases || s.aliases.length === 0) return s.label;
  return [s.label, ...s.aliases].join(" ");
}

function registerSnippets(
  monaco: Monaco,
  language: SnippetLang,
  snippets: SnippetDef[]
) {
  return monaco.languages.registerCompletionItemProvider(language, {
    triggerCharacters: [],
    provideCompletionItems: (model, position) => {
      const word = model.getWordUntilPosition(position);
      const range = {
        startLineNumber: position.lineNumber,
        endLineNumber: position.lineNumber,
        startColumn: word.startColumn,
        endColumn: word.endColumn,
      };
      const suggestions = snippets.map((s, i) => ({
        label: s.label,
        kind: monaco.languages.CompletionItemKind.Snippet,
        insertText: s.body,
        insertTextRules:
          monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
        detail: s.detail,
        documentation: s.documentation,
        filterText: buildFilterText(s),
        sortText: buildSortText(i),
        range,
      }));
      return { suggestions };
    },
  });
}

let registered = false;

export function registerEditorCompletions(monaco: Monaco) {
  if (registered) return;
  registered = true;
  registerSnippets(monaco, "python", PYTHON_SNIPPETS);
  registerSnippets(monaco, "javascript", JS_SNIPPETS);
  registerSnippets(monaco, "java", JAVA_SNIPPETS);
  registerSnippets(monaco, "cpp", CPP_SNIPPETS);
}
